name: Build and Publish

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and publish to pypi
        uses: JRubics/poetry-publish@v1.10
        with:
          python_version: "3.8"
          pypi_token: ${{ secrets.PYPI_API_TOKEN }}
          ignore_dev_requirements: true